{% set package_name = "atef" %}
{% set import_name = "atef" %}
{% set version = load_file_regex(load_file=os.path.join(import_name, "_version.py"), regex_pattern=".*version = '(\S+)'").group(1) %}

package:
  name: {{ package_name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv



requirements:
  build:
  - python >=3.7
  - pip
  - setuptools_scm
  run:
  - python >=3.7
  - apischema
  - archapp >=1.1.0
  - bluesky
  - bluesky-widgets
  - databroker
  - happi
  - ipython
  - numpy
  - ophyd
  - pydm
  - pyyaml
  - qtpy
  - pyqt
  - reportlab
  - rich
  - typhos
  - typing-extensions



test:
  imports:
  - atef
  requires:
  - coverage
  - doctr
  - docs-versions-menu
  - numpydoc
  - flake8
  - pytest
  - pytest-timeout
  - pytest-asyncio
  - pytest-qt
  - pcdsdevices >=7.1.0
  - sphinx
  - sphinx-copybutton
  - sphinx_rtd_theme
  - sphinxcontrib-jquery



about:
  dev_url: https://github.com/pcdshub/atef
  doc_url: https://pcdshub.github.io/atef/
  home: https://github.com/pcdshub/atef
  license: LicenseRef-BSD-3-Clause-SLAC
  summary: Python Automated Test Execution Framework



extra:
  recipe-maintainers:
  - klauer
  - zllentz
  - zrylettc
